### ISSUE TITLE
Add redux library to manage state for posting tweets

### ISSUE THREAD

**Issue by GlitchInMirror** [GlitchInMirror/twitter-clone#1]
Add react-redux to manage state in the application for posting tweets.

**Comment by aldo-rl** [comment]
Hi.
You only need to have redux and you implement the logic to save the tweets?

**Comment by GlitchInMirror** [comment]
No I'll do it later saving and fetching tweets from db. You just implement the state management (react-redux) for adding tweets.

**Comment by aldo-rl** [comment]
I will work on this issue, can you please assign it to me?
